apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashcard-deployment
  labels:
    app: cashcard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cashcard
  template:
    metadata:
      labels:
        app: cashcard
    spec:
      containers:
        - name: cashcard
          image: yassineaoun22/cashcard:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cashcard-service
spec:
  selector:
    app: cashcard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
